on: pull_request

jobs:
  comment_pr:
    permissions: write-all
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: i dont know
        uses: actions/checkout@v3

      - name: mahatv sharma good video
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: useful important trick regarding git hub 
          https://www.youtube.com/shorts/3tTxr9JiWnI
          
          

        
