# This is a basic workflow to help you get started with Actions

on: pull_request

jobs:
  comment_pr:
    permissions: write-all
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment
        uses: Bhupesh-V/memer-action@0.3.0
        
